name: build and deploy demo 
on:
    push:
        branches:
            - main 
    pull_request: 
        types: 
            - opened 
            - synchronize
jobs:
    build_job:
        runs-on: ubuntu-latest 
        if: github.event_name == 'pull_requests'
        steps:
            - name: build application 
              run: echo "building application success....."   
    deploy_job:
        runs-on: ubuntu-latest 
        if: github.event_name == 'push' && github.ref == 'main'
        steps: 
            - name: deploy application inti main 
              run: echo "deploy application ...."                    


