name: github action secreat example 
on: workflow_dispatch
jobs:
    image_push:
        runs-on: ubuntu-latest 
        steps:
            - name: protect password 
              run: "${{secrets.DOCKER_PASS}}"