name: run multiple jobs 
on: workflow_dispatch
jobs:
    test: 
        runs-on: ubuntu-latest 
        steps: 
            - name: running test job 
              run: echo "test job running...." 
    build: 
        runs-on: ubuntu-latest 
        steps: 
            - name: running build job
              run: echo "building job" 
    deploy: 
        runs-on: ubuntu-latest 
        steps: 
            - name: delploy job 
              run: echo "deployed application ...."                     