name: output demo 
on:
    workflow_dispatch 
jobs:
    job1:
        runs-on: ubuntu-latest 
        steps: 
            - name: step one 
              id: step1
              run: echo "version=1.20." >> $GITHUB_OUTPUT
            - name: step two 
              run: echo "deployment version is ${{steps.step1.outputs.version}}"   
   
       
        
        