name: run github action on pull request 
#on:
    push:
        branches:
            - main 
            - developer 
            - '/releae/**'
    pull_request:
        types:
            - opened
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest 
        steps: 
            - name: deployed application 
              run: echo "deployed application"            

