name: share artifact between jobs 
on:
    workflow_dispatch 
jobs: 
    build: 
        outputs:
            version: ${{steps.build.outputs.version}}
        runs-on: ubuntu-latest 
        steps: 
            - name: build application 
              id: build
              run: echo "version:12.56.22" >> $GITHUB_OUTPUT
    deploy: 
        needs: build
        runs-on: ubuntu-latest 
        steps: 
            - name: deploy application 
              run: echo "deploy application version ${{ needs.build.outputs.version }}"              