name: using variable in gitbub actions
on: workflow_dispatch
jobs:
    test_variable:
        runs-on: ubuntu-latest 
        steps: 
            - name: display variable valuers 
              run: |
                echo "${{vars.MY_NAME}}"
